services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=MessagingDB'
      - 'POSTGRES_PASSWORD=ziyad2004L'
      - 'POSTGRES_USER=ziyadsamhaoui'
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - "6379:6379"
