spring.application.name=ApplicationMessagerie

# JWT configuration used for signing tokens
jwt.secret=1cx3NyULn6FPy3ir6JDZ5o392y3LSm1H
# token validity in milliseconds (e.g., 86400000 = 1 day)
jwt.expiration-ms=86400000

